# Generated by Django 6.0.7 on 2026-08-06 16:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='certifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('IA', 'Intelligence Artificielle'), ('Web', 'Développement Web'), ('Mobile', 'Développement Mobile'), ('Data Base', 'Base de Données'), ('DevOps', 'DevOps'), ('UI/UX', 'UI/UX Design'), ('Réseaux', 'Réseaux et Télécommunications'), ('Cybersécurité', 'Cybersécurité'), ('Langue', 'Langue'), ('Gestion de Projet', 'Gestion de Projet'), ('Marketing Digital', 'Marketing Digital'), ('Linux', 'Administration Linux'), ('Data', 'Science des Données'), ('Cloud', 'Cloud Computing'), ('Langage de Programmation', 'Langage de Programmation'), ('Autre', 'Autre')], max_length=100)),
                ('organisme', models.CharField(max_length=100)),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
            },
        ),
        migrations.CreateModel(
            name='Langues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('langue', models.CharField(max_length=50)),
                ('niveau', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
            },
        ),
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('localisation', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('cv', models.TextField(blank=True, null=True)),
                ('formation', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('passions', models.CharField(max_length=100)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter_x', models.URLField(blank=True, null=True)),
                ('tik_tok', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mon Info',
                'verbose_name_plural': 'Mes Infos',
            },
        ),
        migrations.CreateModel(
            name='Projets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('Productivité', 'Productivité'), ('Marketing', 'Marketing'), ('Backend', 'Backend')], max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('doc', models.TextField(blank=True, null=True)),
                ('code_source', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_app', models.CharField(max_length=100)),
                ('mode_maintenance', models.BooleanField(default=False)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cle_api_portfolio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competence', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(default='Utilisateur', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('dfa', models.BooleanField(default=True)),
                ('validate_code', models.CharField(blank=True, max_length=6, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='URL consultée (ex: /projects/my-app/)', max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('referrer', models.URLField(blank=True, help_text="Site d'origine du visiteur", max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP (peut être anonymisée)', null=True)),
                ('user_agent', models.CharField(blank=True, help_text="Navigateur / Système d'exploitation", max_length=255, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot / Crawler'), ('other', 'Autre')], default='other', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Page vue',
                'verbose_name_plural': 'Pages vues',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['path', 'timestamp'], name='api_dashboa_path_8495c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skills_list',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=20)),
                ('pourcentage', models.IntegerField(help_text='Entrez un nombre entier entre 1 et 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_list', to='api.skills')),
            ],
            options={
                'verbose_name': 'Liste de compétences',
                'verbose_name_plural': 'Listes de compétences',
            },
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tec_projets', to='api.projets')),
                ('technologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tec_skills', to='api.skills_list')),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
            },
        ),
    ]
