# Generated by Django 6.0.7 on 2026-08-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='cle_api_portfolio',
        ),
    ]
