# Generated by Django 6.0.7 on 2026-08-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_settings_cle_api_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='certifications',
            new_name='Certificates',
        ),
        migrations.RenameModel(
            old_name='Projets',
            new_name='Projects',
        ),
    ]
