# Generated by Django 6.0.7 on 2026-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_username_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='categorie',
            field=models.CharField(choices=[('Web', 'Application Web'), ('Mobile', 'Application Mobile'), ('Desktop', 'Application Desktop'), ('Data base', 'Base de Données'), ('IA', 'Intelligence Artificielle'), ('DevOps', 'DevOps'), ('UI/UX', 'UI/UX Design'), ('Réseaux', 'Réseaux et Télécommunications'), ('Cybersécurité', 'Cybersécurité'), ('API', 'API'), ('Autre', 'Autre')], max_length=100),
        ),
    ]
