# Generated by Django 6.0.7 on 2026-08-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_projects_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-08-11 10:36:00.000000'),
            preserve_default=False,
        ),
    ]
