# Generated by Django 6.0.7 on 2026-08-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_journal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/images/'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='myinfo/cv/'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myinfo/photos/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='projects/docs/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
    ]
