# Generated by Django 6.0.7 on 2026-08-14 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_certificates_image_alter_myinfo_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='annee',
        ),
        migrations.AddField(
            model_name='certificates',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
