# Generated by Django 6.0.7 on 2026-08-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_certificates_annee_certificates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='notification_email',
            field=models.BooleanField(default=True),
        ),
    ]
