# Generated by Django 6.0.7 on 2026-08-22 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_settings_notification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='path',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='referrer',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
