# Generated by Django 6.0.7 on 2026-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_dashboard_id_alter_dashboard_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
