# Generated by Django 5.2 on 2025-05-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_myinfo_projets_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='static/cv/'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
