# Generated by Django 5.2 on 2025-05-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0004_alter_myinfo_cv_alter_myinfo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='Competence',
            new_name='competence',
        ),
    ]
