# Generated by Django 5.2 on 2025-05-12 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0005_rename_competence_skills_competence'),
    ]

    operations = [
        migrations.AddField(
            model_name='projets',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills_list',
            name='pourcentage',
            field=models.IntegerField(help_text='Entrez un nombre entier entre 1 et 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
