# Generated by Django 5.2 on 2025-05-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0006_projets_demo_alter_skills_list_pourcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/projets/'),
        ),
    ]
