# Generated by Django 5.2 on 2025-05-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0007_alter_projets_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologies',
            name='nom',
        ),
        migrations.AddField(
            model_name='technologies',
            name='technologie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tec_skills', to='mailapp.skills_list'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technologies',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tec_projets', to='mailapp.projets'),
        ),
    ]
