# Generated by Django 5.2 on 2025-05-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0008_remove_technologies_nom_technologies_technologie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projets',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
