# Generated by Django 5.2 on 2025-05-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0009_projets_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='media/cv/'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profil/'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='media/docs/'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/imaProjets/'),
        ),
    ]
