# Generated by Django 5.2 on 2025-05-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0010_alter_myinfo_cv_alter_myinfo_image_alter_projets_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='static/cv/'),
        ),
        migrations.AlterField(
            model_name='myinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='static/docs/'),
        ),
        migrations.AlterField(
            model_name='projets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/projets/'),
        ),
    ]
